/**
 * AiFeatureTemplate.js
 *
 * These are the ready-to-use code snippets that get injected into every
 * application generated by Extern AI.
 *
 * The AI uses these templates as a reference when scaffolding new apps —
 * it will adapt variable names and styles to fit the app being built,
 * but the core logic (auth, token tracking, proxy calls) stays the same.
 */

// ─── 1. Automated Backend Infrastructure (Firebase) ───────────────────────
// Injected as: src/firebase.js
export const FIREBASE_INIT_TEMPLATE = `
import { initializeApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getStorage } from 'firebase/storage';

// Automated Backend Config — provided automatically by Extern AI
const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: import.meta.env.VITE_FIREBASE_APP_ID,
};

// Initialize automated backend infrastructure
export const app = initializeApp(firebaseConfig);
export const db = getFirestore(app);
export const storage = getStorage(app);

// Note: Authentication is not enforced by default.
// If the user requests user login, import getAuth from 'firebase/auth' here.
`;

// ─── 2. Environment Config Template ───────────────────────────────────────
// Injected as: .env
export const ENV_TEMPLATE = `
VITE_APP_ID=%%APP_ID%%
VITE_AI_PROXY_URL=https://api.externai.com
`;

// ─── 2. AI Service — proxy client ─────────────────────────────────────────
// Injected as: src/services/aiService.js
export const AI_SERVICE_TEMPLATE = `
// The Extern AI backend acts as a secure proxy — your API key never leaves the server
const AI_PROXY_URL = import.meta.env.VITE_AI_PROXY_URL || 'http://localhost:5000';
const APP_ID = import.meta.env.VITE_APP_ID;

const headers = () => ({
  'Content-Type': 'application/json',
  'X-App-Id': APP_ID,
});

// ── Chat with the AI ──────────────────────────────────────────────────────
export async function chat(messages, systemPrompt = '') {
  const res = await fetch(\`\${AI_PROXY_URL}/api/generated-app/chat\`, {
    method: 'POST',
    headers: headers(),
    body: JSON.stringify({ messages, systemPrompt }),
  });
  const data = await res.json();
  if (res.status === 402) throw { code: 'TOKEN_LIMIT_REACHED', ...data };
  if (!res.ok) throw new Error(data.error || 'AI request failed');
  return data; // { reply, tokensUsed, tokensTotal, freeLimit }
}

// ── Upload a document for RAG (PDF / plain text) ──────────────────────────
export async function uploadDocument(file) {
  const form  = new FormData();
  form.append('file', file);

  const res = await fetch(\`\${AI_PROXY_URL}/api/generated-app/documents\`, {
    method: 'POST',
    headers: { 'X-App-Id': APP_ID },
    body: form,
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.error || 'Upload failed');
  return data; // { success, documentId, fileName, chunksIndexed }
}

// ── Ask a question about uploaded documents (RAG) ─────────────────────────
export async function queryDocuments(question, documentId = null) {
  const res = await fetch(\`\${AI_PROXY_URL}/api/generated-app/query\`, {
    method: 'POST',
    headers: headers(),
    body: JSON.stringify({ question, documentId }),
  });
  const data = await res.json();
  if (res.status === 402) throw { code: 'TOKEN_LIMIT_REACHED', ...data };
  if (!res.ok) throw new Error(data.error || 'Query failed');
  return data; // { answer, tokensUsed, tokensTotal, freeLimit, sourceContext }
}

// ── Fetch current token usage for the logged-in user ─────────────────────
export async function getUsage() {
  const res = await fetch(\`\${AI_PROXY_URL}/api/generated-app/usage\`, {
    headers: headers(),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.error || 'Could not fetch usage');
  return data; // { tier, tokensUsed, freeLimit, tokensRemaining, limitReached }
}
`;


// ─── 3. AI Chat UI Component ──────────────────────────────────────────────
// Injected as: src/components/AiChat.jsx
export const AI_CHAT_COMPONENT_TEMPLATE = `
import React, { useState, useRef, useEffect } from 'react';
import { chat } from '../services/aiService';

export default function AiChat({ systemPrompt = 'You are a helpful AI assistant.' }) {
  const [messages,  setMessages]  = useState([]);
  const [input,     setInput]     = useState('');
  const [loading,   setLoading]   = useState(false);
  const [error,     setError]     = useState(null);
  const [limitHit,  setLimitHit]  = useState(false);
  const [usage,     setUsage]     = useState(null);
  const bottomRef = useRef(null);

  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages]);

  const sendMessage = async () => {
    const text = input.trim();
    if (!text || loading || limitHit) return;

    const userMsg = { role: 'user', content: text };
    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setLoading(true);
    setError(null);

    try {
      const history = [...messages, userMsg].map(m => ({ role: m.role, content: m.content }));
      const result  = await chat(history, systemPrompt);

      setMessages(prev => [...prev, { role: 'assistant', content: result.reply }]);
      setUsage({ tokensUsed: result.tokensTotal, freeLimit: result.freeLimit });
    } catch (err) {
      if (err.code === 'TOKEN_LIMIT_REACHED') {
        setLimitHit(true);
        setError(err.message);
      } else {
        setError(err.message || 'Something went wrong. Please try again.');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleKey = (e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage(); } };

  return (
    <div className="ai-chat-container">
      {/* Message history */}
      <div className="ai-chat-messages">
        {messages.length === 0 && (
          <div className="ai-chat-empty">
            <span>✨ AI Assistant</span>
            <p>Ask me anything!</p>
          </div>
        )}
        {messages.map((m, i) => (
          <div key={i} className={\`ai-chat-message \${m.role}\`}>
            <span className="ai-chat-role">{m.role === 'user' ? 'You' : 'AI'}</span>
            <p>{m.content}</p>
          </div>
        ))}
        {loading && (
          <div className="ai-chat-message assistant ai-chat-thinking">
            <span className="ai-chat-role">AI</span>
            <p>Thinking…</p>
          </div>
        )}
        <div ref={bottomRef} />
      </div>

      {/* Token usage bar */}
      {usage && (
        <div className="ai-usage-bar">
          <div
            className="ai-usage-fill"
            style={{ width: \`\${Math.min(100, (usage.tokensUsed / usage.freeLimit) * 100)}%\` }}
          />
          <span className="ai-usage-label">
            {usage.tokensUsed.toLocaleString()} / {usage.freeLimit.toLocaleString()} free tokens used
          </span>
        </div>
      )}

      {/* Limit reached banner */}
      {limitHit && (
        <div className="ai-limit-banner">
          <p>🚀 You've used all your free AI tokens.</p>
          <a href="https://externai.com/upgrade" target="_blank" rel="noopener noreferrer">
            Upgrade to Pro — unlimited AI for $9.99/mo
          </a>
        </div>
      )}

      {/* Error */}
      {error && !limitHit && <p className="ai-error">{error}</p>}

      {/* Input */}
      <div className="ai-chat-input-row">
        <textarea
          className="ai-chat-input"
          rows={2}
          value={input}
          onChange={e => setInput(e.target.value)}
          onKeyDown={handleKey}
          placeholder={limitHit ? 'Upgrade to continue chatting…' : 'Type a message…'}
          disabled={loading || limitHit}
        />
        <button
          className="ai-chat-send"
          onClick={sendMessage}
          disabled={loading || limitHit || !input.trim()}
        >
          {loading ? '…' : 'Send'}
        </button>
      </div>
    </div>
  );
}
`;

// ─── 4. Document Upload + RAG Component ───────────────────────────────────
// Injected as: src/components/AiDocSearch.jsx
export const AI_DOC_SEARCH_TEMPLATE = `
import React, { useState } from 'react';
import { uploadDocument, queryDocuments } from '../services/aiService';

export default function AiDocSearch() {
  const [docId,    setDocId]    = useState(null);
  const [fileName, setFileName] = useState('');
  const [question, setQuestion] = useState('');
  const [answer,   setAnswer]   = useState('');
  const [loading,  setLoading]  = useState(false);
  const [status,   setStatus]   = useState('');
  const [limitHit, setLimitHit] = useState(false);

  const handleUpload = async (e) => {
    const file = e.target.files[0];
    if (!file) return;
    setLoading(true);
    setStatus('Indexing document…');
    try {
      const result = await uploadDocument(file);
      setDocId(result.documentId);
      setFileName(result.fileName);
      setStatus(\`✅ "\${result.fileName}" indexed (\${result.chunksIndexed} sections)\`);
    } catch (err) {
      setStatus('❌ Upload failed: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleQuery = async () => {
    if (!question.trim() || !docId || loading || limitHit) return;
    setLoading(true);
    setAnswer('');
    try {
      const result = await queryDocuments(question, docId);
      setAnswer(result.answer);
    } catch (err) {
      if (err.code === 'TOKEN_LIMIT_REACHED') {
        setLimitHit(true);
        setAnswer(err.message);
      } else {
        setAnswer('Error: ' + err.message);
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="ai-doc-search">
      <h3>📄 Ask Your Documents</h3>
      <label className="ai-upload-btn">
        {loading ? 'Processing…' : fileName ? \`📎 \${fileName}\` : '+ Upload Document'}
        <input type="file" accept=".txt,.md,.csv,.json" onChange={handleUpload} hidden />
      </label>
      {status && <p className="ai-upload-status">{status}</p>}

      {docId && (
        <div className="ai-query-row">
          <input
            className="ai-query-input"
            value={question}
            onChange={e => setQuestion(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && handleQuery()}
            placeholder="Ask a question about your document…"
            disabled={loading || limitHit}
          />
          <button className="ai-query-btn" onClick={handleQuery} disabled={loading || limitHit}>
            {loading ? '…' : 'Ask'}
          </button>
        </div>
      )}
      {answer && <div className="ai-answer"><strong>Answer:</strong> {answer}</div>}
      {limitHit && (
        <a className="ai-upgrade-link" href="https://externai.com/upgrade">
          Upgrade to Pro for unlimited AI →
        </a>
      )}
    </div>
  );
}
`;

// ─── 5. Environment variables template ────────────────────────────────────
// Injected as: .env  (populated by Extern AI during project setup)
export const ENV_TEMPLATE = `
VITE_AI_PROXY_URL=http://localhost:5000
VITE_APP_ID=your_generated_app_id
`;

export default {
  FIREBASE_INIT_TEMPLATE,
  AI_SERVICE_TEMPLATE,
  AI_CHAT_COMPONENT_TEMPLATE,
  AI_DOC_SEARCH_TEMPLATE,
  ENV_TEMPLATE,
};
