/**
 * AiFeatureTemplate.js
 *
 * These are the ready-to-use code snippets that get injected into every
 * application generated by Extern AI.
 *
 * Architecture:
 * - Firebase (Firestore) is installed from the FIRST response
 * - The AI chat feature calls the Extern AI Cloud Function endpoint
 *   which uses OpenAI GPT-4o-mini (centrally managed — users never need their own key)
 * - All chat history is saved to Firestore
 */

// ─── 1. Firebase Initialization ───────────────────────────────────────────
// Injected as: src/firebase.js
export const FIREBASE_INIT_TEMPLATE = `
import { initializeApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getStorage } from 'firebase/storage';
import { getAuth, signInAnonymously } from 'firebase/auth';

// Extern AI — centrally managed Firebase backend
const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: import.meta.env.VITE_FIREBASE_APP_ID,
};

export const app = initializeApp(firebaseConfig);
export const db = getFirestore(app);
export const storage = getStorage(app);
export const auth = getAuth(app);

let authPromise = null;
export const ensureAuthenticated = async () => {
  if (auth.currentUser) return auth.currentUser;
  if (!authPromise) {
    authPromise = signInAnonymously(auth).then(userCred => userCred.user);
  }
  return authPromise;
};

// ── Auto-initialize auth silently on app load ─────────────────────────────
// This guarantees request.auth != null for ALL Firebase operations,
// even if the builder did not add user authentication to their app.
// If the builder DID add their own auth (email/password, Google, etc.),
// that login will automatically replace this anonymous session.
ensureAuthenticated().catch(() => {});
`;

// ─── 2. Environment Config Template ───────────────────────────────────────
// Injected as: .env
export const ENV_TEMPLATE = `
VITE_APP_ID=%%APP_ID%%

# Extern AI — Firebase backend (shared, centrally managed)
VITE_FIREBASE_API_KEY=AIzaSyD8Btf2_059GXESh1axlJl6n7OLSsgjcqM
VITE_FIREBASE_AUTH_DOMAIN=externai-desktop.firebaseapp.com
VITE_FIREBASE_PROJECT_ID=externai-desktop
VITE_FIREBASE_STORAGE_BUCKET=externai-desktop.firebasestorage.app
VITE_FIREBASE_MESSAGING_SENDER_ID=905625488730
VITE_FIREBASE_APP_ID=1:905625488730:web:a1fbbe4260c6cea98d3763
`;

// ─── 3. AI Service — calls Cloud Function, saves to Firestore ────────────
// Injected as: src/services/aiService.js
export const AI_SERVICE_TEMPLATE = `
import { db, storage, auth, ensureAuthenticated } from '../firebase';
import { collection, addDoc, getDocs, query, orderBy, serverTimestamp } from 'firebase/firestore';
import { ref, uploadBytesResumable } from 'firebase/storage';

// Extern AI centrally-managed AI proxy (OpenAI GPT-4o-mini — no key needed)
const AI_FUNCTION_URL = 'https://api-bkrpnxig4a-uc.a.run.app/api/generated-app';
const APP_ID = import.meta.env.VITE_APP_ID || 'default-app';

const headers = () => ({
  'Content-Type': 'application/json',
  'X-App-Id': APP_ID,
});

// ── Chat with the AI ──────────────────────────────────────────────────────
export async function chat(messages, systemPrompt = '') {
  const res = await fetch(\`\${AI_FUNCTION_URL}/chat\`, {
    method: 'POST',
    headers: headers(),
    body: JSON.stringify({ messages, systemPrompt }),
  });
  const data = await res.json();
  if (res.status === 402) throw { code: 'TOKEN_LIMIT_REACHED', ...data };
  if (!res.ok) throw new Error(data.error || 'AI request failed');

  // Save conversation to Firestore
  try {
    const user = await ensureAuthenticated();
    const lastUserMsg = messages[messages.length - 1];
    await addDoc(collection(db, 'users', user.uid, 'chatHistory'), {
      appId: APP_ID,
      userMessage: lastUserMsg?.content || '',
      aiReply: data.reply,
      tokensUsed: data.tokensUsed || 0,
      timestamp: serverTimestamp(),
    });
  } catch (e) {
    // Non-blocking — don't fail the chat if Firestore write fails
    console.warn('[AI] Could not save to Firestore:', e.message);
  }

  return data; // { reply, tokensUsed, tokensTotal, freeLimit }
}

// ── Load chat history from Firestore ─────────────────────────────────────
export async function loadChatHistory(limitCount = 50) {
  try {
    const user = await ensureAuthenticated();
    const q = query(
      collection(db, 'users', user.uid, 'chatHistory'),
      orderBy('timestamp', 'desc'),
    );
    const snap = await getDocs(q);
    return snap.docs
      .map(d => d.data())
      .filter(d => d.appId === APP_ID)
      .slice(0, limitCount)
      .reverse();
  } catch (e) {
    console.warn('[AI] Could not load history:', e.message);
    return [];
  }
}

// ── Document Parsers (Lazy Loaded) ────────────────────────────────────────
const loadPdfJs = async () => {
  if (window.pdfjsLib) return window.pdfjsLib;
  return new Promise((resolve, reject) => {
    const script = document.createElement('script');
    script.src = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.16.105/pdf.min.js';
    script.onload = () => {
      window.pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.16.105/pdf.worker.min.js';
      resolve(window.pdfjsLib);
    };
    script.onerror = reject;
    document.head.appendChild(script);
  });
};

const loadMammoth = async () => {
  if (window.mammoth) return window.mammoth;
  return new Promise((resolve, reject) => {
    const script = document.createElement('script');
    script.src = 'https://cdnjs.cloudflare.com/ajax/libs/mammoth/1.5.1/mammoth.browser.min.js';
    script.onload = () => resolve(window.mammoth);
    script.onerror = reject;
    document.head.appendChild(script);
  });
};

async function extractText(file) {
  const ext = file.name.split('.').pop().toLowerCase();
  
  if (['txt', 'md', 'csv', 'json'].includes(ext)) {
    return await file.text();
  }
  
  if (ext === 'pdf') {
    const pdfjs = await loadPdfJs();
    const arrayBuffer = await file.arrayBuffer();
    const pdf = await pdfjs.getDocument(arrayBuffer).promise;
    let fullText = '';
    for (let i = 1; i <= pdf.numPages; i++) {
      const page = await pdf.getPage(i);
      const content = await page.getTextContent();
      const pageText = content.items.map(item => item.str).join(' ');
      fullText += pageText + '\\n';
    }
    return fullText;
  }
  
  if (ext === 'docx') {
    const mammoth = await loadMammoth();
    const arrayBuffer = await file.arrayBuffer();
    const result = await mammoth.extractRawText({ arrayBuffer });
    return result.value;
  }
  
  throw new Error('Unsupported file type for text extraction');
}

// ── Upload a document for RAG (PDF / plain text) ──────────────────────────
export async function uploadDocument(file, onProgress) {
  return new Promise(async (resolve, reject) => {
    try {
      const user = await ensureAuthenticated();
      // 1. Upload to Firebase Storage
      const storageRef = ref(storage, \`user_files/\${user.uid}/\${Date.now()}_\${file.name}\`);
    const uploadTask = uploadBytesResumable(storageRef, file);

    uploadTask.on(
      'state_changed',
      (snapshot) => {
        const progress = Math.round((snapshot.bytesTransferred / snapshot.totalBytes) * 100);
        if (onProgress) onProgress(progress);
      },
      (error) => {
        reject(error);
      },
      async () => {
        // 2. Upload complete, extract text client-side
        if (onProgress) onProgress(100);
        try {
          const text = await extractText(file);
          // 3. Cache extracted text locally (bypass CORS/backend parsing completely)
          localStorage.setItem(\`doc_\${storageRef.fullPath}\`, text);
          
          resolve({ documentId: storageRef.fullPath, fileName: file.name, chunksIndexed: 1 });
        } catch (err) {
          reject(err);
        }
      }
    );
    } catch (err) {
      reject(err);
    }
  });
}

// ── Ask a question about uploaded documents (RAG) ─────────────────────────
export async function queryDocuments(question, documentId = null) {
  // Read from localStorage cache
  const text = localStorage.getItem(\`doc_\${documentId}\`);
  if (!text) throw new Error('Document text not found in local cache');
  
  // Cap at ~20,000 characters to prevent hitting token limits
  const safeText = text.substring(0, 20000);
  
  const messages = [
    { role: 'system', content: \`Answer the user's question based strictly on the following document:\n\n\${safeText}\` },
    { role: 'user', content: question }
  ];
  
  const res = await fetch(\`\${AI_FUNCTION_URL}/chat\`, {
    method: 'POST',
    headers: headers(),
    body: JSON.stringify({ messages }),
  });
  
  const data = await res.json();
  if (res.status === 402) throw { code: 'TOKEN_LIMIT_REACHED', ...data };
  if (!res.ok) throw new Error(data.error || 'Query failed');
  
  return { answer: data.reply };
}

// ── Fetch current token usage ─────────────────────────────────────────────
export async function getUsage() {
  const res = await fetch(\`\${AI_FUNCTION_URL}/usage\`, { headers: headers() });
  const data = await res.json();
  if (!res.ok) throw new Error(data.error || 'Could not fetch usage');
  return data;
}
`;


// ─── 4. AI Chat UI Component ──────────────────────────────────────────────
// Injected as: src/components/AiChat.jsx
export const AI_CHAT_COMPONENT_TEMPLATE = `
import React, { useState, useRef, useEffect } from 'react';
import { chat, loadChatHistory } from '../services/aiService';

export default function AiChat({ systemPrompt = 'You are a helpful AI assistant.' }) {
  const [messages,  setMessages]  = useState([]);
  const [input,     setInput]     = useState('');
  const [loading,   setLoading]   = useState(false);
  const [error,     setError]     = useState(null);
  const [limitHit,  setLimitHit]  = useState(false);
  const [usage,     setUsage]     = useState(null);
  const bottomRef = useRef(null);

  // Load chat history from Firestore on mount
  useEffect(() => {
    loadChatHistory().then(history => {
      if (history.length > 0) {
        const restored = history.flatMap(h => [
          { role: 'user',      content: h.userMessage },
          { role: 'assistant', content: h.aiReply },
        ]);
        setMessages(restored);
      }
    });
  }, []);

  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages]);

  const sendMessage = async () => {
    const text = input.trim();
    if (!text || loading || limitHit) return;

    const userMsg = { role: 'user', content: text };
    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setLoading(true);
    setError(null);

    try {
      const history = [...messages, userMsg].map(m => ({ role: m.role, content: m.content }));
      const result  = await chat(history, systemPrompt);

      setMessages(prev => [...prev, { role: 'assistant', content: result.reply }]);
      setUsage({ tokensUsed: result.tokensTotal, freeLimit: result.freeLimit });
    } catch (err) {
      if (err.code === 'TOKEN_LIMIT_REACHED') {
        setLimitHit(true);
        setError(err.message);
      } else {
        setError(err.message || 'Something went wrong. Please try again.');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleKey = (e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage(); } };

  return (
    <div className="ai-chat-container">
      <div className="ai-chat-messages">
        {messages.length === 0 && (
          <div className="ai-chat-empty">
            <span>✨ AI Assistant</span>
            <p>Ask me anything! Your conversations are saved automatically.</p>
          </div>
        )}
        {messages.map((m, i) => (
          <div key={i} className={\`ai-chat-message \${m.role}\`}>
            <span className="ai-chat-role">{m.role === 'user' ? 'You' : 'AI'}</span>
            <p>{m.content}</p>
          </div>
        ))}
        {loading && (
          <div className="ai-chat-message assistant ai-chat-thinking">
            <span className="ai-chat-role">AI</span>
            <p>Thinking…</p>
          </div>
        )}
        <div ref={bottomRef} />
      </div>

      {usage && (
        <div className="ai-usage-bar">
          <div
            className="ai-usage-fill"
            style={{ width: \`\${Math.min(100, (usage.tokensUsed / usage.freeLimit) * 100)}%\` }}
          />
          <span className="ai-usage-label">
            {usage.tokensUsed.toLocaleString()} / {usage.freeLimit.toLocaleString()} free tokens used
          </span>
        </div>
      )}

      {limitHit && (
        <div className="ai-limit-banner">
          <p>🚀 You've used all your free AI tokens.</p>
          <a href="https://externai.com/upgrade" target="_blank" rel="noopener noreferrer">
            Upgrade to Pro — unlimited AI for $9.99/mo
          </a>
        </div>
      )}

      {error && !limitHit && <p className="ai-error">{error}</p>}

      <div className="ai-chat-input-row">
        <textarea
          className="ai-chat-input"
          rows={2}
          value={input}
          onChange={e => setInput(e.target.value)}
          onKeyDown={handleKey}
          placeholder={limitHit ? 'Upgrade to continue chatting…' : 'Type a message…'}
          disabled={loading || limitHit}
        />
        <button
          className="ai-chat-send"
          onClick={sendMessage}
          disabled={loading || limitHit || !input.trim()}
        >
          {loading ? '…' : 'Send'}
        </button>
      </div>
    </div>
  );
}
`;

// ─── 5. Document Upload + RAG Component ───────────────────────────────────
// Injected as: src/components/AiDocSearch.jsx
export const AI_DOC_SEARCH_TEMPLATE = `
import React, { useState } from 'react';
import { uploadDocument, queryDocuments } from '../services/aiService';

export default function AiDocSearch() {
  const [docId,    setDocId]    = useState(null);
  const [fileName, setFileName] = useState('');
  const [question, setQuestion] = useState('');
  const [answer,   setAnswer]   = useState('');
  const [loading,  setLoading]  = useState(false);
  const [status,   setStatus]   = useState('');
  const [limitHit, setLimitHit] = useState(false);
  const [progress, setProgress] = useState(0);

  const handleUpload = async (e) => {
    const file = e.target.files[0];
    if (!file) return;
    setLoading(true);
    setProgress(0);
    setStatus('Uploading... 0%');
    try {
      const result = await uploadDocument(file, (p) => {
        setProgress(p);
        setStatus(p < 100 ? \`Uploading... \${p}%\` : 'Indexing document...');
      });
      setDocId(result.documentId);
      setFileName(result.fileName);
      setStatus(\`✅ "\${result.fileName}" indexed (\${result.chunksIndexed} sections)\`);
    } catch (err) {
      setStatus('❌ Upload failed: ' + err.message);
    } finally {
      setLoading(false);
      setProgress(0);
    }
  };

  const handleQuery = async () => {
    if (!question.trim() || !docId || loading || limitHit) return;
    setLoading(true);
    setAnswer('');
    try {
      const result = await queryDocuments(question, docId);
      setAnswer(result.answer);
    } catch (err) {
      if (err.code === 'TOKEN_LIMIT_REACHED') {
        setLimitHit(true);
        setAnswer(err.message);
      } else {
        setAnswer('Error: ' + err.message);
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="ai-doc-search">
      <h3>📄 Ask Your Documents</h3>
      <label className="ai-upload-btn">
        {loading ? (progress > 0 && progress < 100 ? \`Uploading \${progress}%\` : 'Processing…') : fileName ? \`📎 \${fileName}\` : '+ Upload Document'}
        <input type="file" accept=".txt,.md,.csv,.json" onChange={handleUpload} hidden />
      </label>
      
      {loading && progress > 0 && progress < 100 && (
        <div style={{ width: '100%', height: '4px', background: 'rgba(255,255,255,0.1)', borderRadius: '2px', marginTop: '8px', overflow: 'hidden' }}>
          <div style={{ width: \`\${progress}%\`, height: '100%', background: '#6366f1', borderRadius: '2px', transition: 'width 0.2s ease-out' }} />
        </div>
      )}
      
      {status && <p className="ai-upload-status">{status}</p>}

      {docId && (
        <div className="ai-query-row">
          <input
            className="ai-query-input"
            value={question}
            onChange={e => setQuestion(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && handleQuery()}
            placeholder="Ask a question about your document…"
            disabled={loading || limitHit}
          />
          <button className="ai-query-btn" onClick={handleQuery} disabled={loading || limitHit}>
            {loading ? '…' : 'Ask'}
          </button>
        </div>
      )}
      {answer && <div className="ai-answer"><strong>Answer:</strong> {answer}</div>}
      {limitHit && (
        <a className="ai-upgrade-link" href="https://externai.com/upgrade">
          Upgrade to Pro for unlimited AI →
        </a>
      )}
    </div>
  );
}
`;


export default {
  FIREBASE_INIT_TEMPLATE,
  AI_SERVICE_TEMPLATE,
  AI_CHAT_COMPONENT_TEMPLATE,
  AI_DOC_SEARCH_TEMPLATE,
  ENV_TEMPLATE,
};
