/**
 * Firebase Multi-Tenant Manager
 *
 * Handles automatic tenant provisioning for every app generated by Extern AI.
 * Each generated app gets its own Firebase Identity Platform tenant, meaning
 * end-users are completely isolated at the auth level — not just data level.
 *
 * Requires: Google Cloud Identity Platform enabled on the Firebase project.
 * Enable at: https://console.cloud.google.com/customer-identity
 *
 * Firestore schema:
 *   generatedAppTenants/{appId} → { tenantId, appName, createdAt, createdBy }
 */

const admin = require('firebase-admin');
const db = admin.firestore();

/**
 * Create a new Firebase Identity Platform tenant for a generated app.
 * Called once when an app is first generated.
 *
 * @param {string} appId     - Unique ID for the generated app (e.g. UUID)
 * @param {string} appName   - Human-readable name of the app
 * @param {string} createdBy - Extern AI user ID who created the app
 * @returns {{ tenantId: string, appId: string }}
 */
async function provisionTenant(appId, appName, createdBy) {
  // Check if tenant already exists for this appId
  const existing = await db.collection('generatedAppTenants').doc(appId).get();
  if (existing.exists) {
    console.log(`[MultiTenant] Tenant already exists for app ${appId}: ${existing.data().tenantId}`);
    return { tenantId: existing.data().tenantId, appId };
  }

  // Create a new Identity Platform tenant
  const tenant = await admin.auth().tenantManager().createTenant({
    displayName: appName || `ExternAI App — ${appId}`,
    emailSignInConfig: {
      enabled: true,
      passwordRequired: true,
    },
    // Allow Google sign-in too (optional — can be extended)
    multiFactorConfig: {
      state: 'DISABLED',
    },
  });

  const tenantId = tenant.tenantId;
  console.log(`[MultiTenant] Created tenant ${tenantId} for app ${appId}`);

  // Store the mapping in Firestore
  await db.collection('generatedAppTenants').doc(appId).set({
    tenantId,
    appId,
    appName: appName || `App ${appId}`,
    createdBy,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
  });

  return { tenantId, appId };
}

/**
 * Retrieve the tenant ID for a given generated app.
 * Returns null if the app has no tenant yet.
 *
 * @param {string} appId
 * @returns {string|null}
 */
async function getTenantId(appId) {
  const doc = await db.collection('generatedAppTenants').doc(appId).get();
  if (!doc.exists) return null;
  return doc.data().tenantId;
}

/**
 * Verify a Firebase ID token issued under a specific tenant.
 * This is the secure multi-tenant version of token verification —
 * it ensures the user actually belongs to the correct app's tenant.
 *
 * @param {string} idToken  - Firebase ID token from the client
 * @param {string} tenantId - Expected tenant ID for this app
 * @returns {admin.auth.DecodedIdToken}
 */
async function verifyTenantToken(idToken, tenantId) {
  const tenantAuth = admin.auth().tenantManager().authForTenant(tenantId);
  const decoded = await tenantAuth.verifyIdToken(idToken);

  // Extra safety: confirm the token's tenant matches the expected tenant
  if (decoded.firebase?.tenant !== tenantId) {
    throw new Error(`Token tenant mismatch: expected ${tenantId}, got ${decoded.firebase?.tenant}`);
  }

  return decoded;
}

/**
 * Delete a tenant and all its users (called if a generated app is deleted).
 *
 * @param {string} appId
 */
async function deprovisionTenant(appId) {
  const tenantId = await getTenantId(appId);
  if (!tenantId) {
    console.warn(`[MultiTenant] No tenant found for app ${appId}, nothing to delete`);
    return;
  }

  await admin.auth().tenantManager().deleteTenant(tenantId);
  await db.collection('generatedAppTenants').doc(appId).delete();
  console.log(`[MultiTenant] Deleted tenant ${tenantId} for app ${appId}`);
}

module.exports = { provisionTenant, getTenantId, verifyTenantToken, deprovisionTenant };
