/**
 * Generated App AI Proxy
 * 
 * Provides a secure AI backend for every application generated by Extern AI.
 * 
 * Features:
 * - Firebase multi-tenant auth: each generated app has its own tenant ID
 * - 20,000 free token limit per end-user tracked in Firestore
 * - GPT-4o-mini for all AI calls (low cost, high quality)
 * - RAG (Retrieval-Augmented Generation) via Firebase Vector Search:
 *     - POST /api/generated-app/documents  → upload & chunk documents
 *     - POST /api/generated-app/query      → semantic search + AI answer
 * - POST /api/generated-app/chat          → general AI chat
 * - GET  /api/generated-app/usage         → token usage for current user
 */

const express = require('express');
const router = express.Router();
const admin = require('firebase-admin');

// ── Constants ──────────────────────────────────────────────────────────────
const OPENAI_API_KEY = process.env.GENERATED_APP_OPENAI_KEY;
const GPT_MODEL = 'gpt-4o-mini';
const FREE_TOKEN_LIMIT = parseInt(process.env.FREE_TOKEN_LIMIT) || 2000000;
const EMBEDDING_MODEL = 'text-embedding-3-small';
const CHUNK_SIZE = 2000;      // characters (~500 tokens)
const CHUNK_OVERLAP = 200;
const TOP_K_CHUNKS = 4;       // how many chunks to retrieve for RAG

const db = admin.firestore();

// ── Helpers ────────────────────────────────────────────────────────────────

/**
 * Get or create a token-usage document for a generated app.
 * Stored under: generatedAppUsage/{appId}
 */
async function getOrCreateAppUsage(appId) {
  const ref = db.collection('generatedAppUsage').doc(appId);
  const snap = await ref.get();
  
  if (!snap.exists) {
    const data = {
      appId,
      tokensUsed: 0,
      tier: 'free',
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    };
    await ref.set(data);
    return data;
  }
  return snap.data();
}

/**
 * Atomically add tokens to an app's running total.
 */
async function incrementAppTokens(appId, tokens) {
  const ref = db.collection('generatedAppUsage').doc(appId);
  await ref.update({
    tokensUsed: admin.firestore.FieldValue.increment(tokens),
    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
  });
}

/**
 * Check if the app is within its free token limit (or is on a paid tier).
 */
function isWithinLimit(usage) {
  if (usage.tier !== 'free') return true;
  return (usage.tokensUsed || 0) < FREE_TOKEN_LIMIT;
}


/**
 * Call the DeepSeek API for Chat Completions.
 */
async function callOpenAI(messages, maxTokens = 1000) {
  const DEEPSEEK_API_KEY = process.env.DEEPSEEK_API_KEY || '';

  const response = await fetch('https://api.deepseek.com/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${DEEPSEEK_API_KEY}`,
    },
    body: JSON.stringify({
      model: 'deepseek-v4-pro',
      messages,
      max_tokens: maxTokens,
      temperature: 1,          // DeepSeek recommends temp=1 when reasoning is enabled
      reasoning_effort: 'max', // Full chain-of-thought reasoning
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`DeepSeek error ${response.status}: ${err}`);
  }
  const data = await response.json();
  return data;
}

/**
 * Generate a text embedding using OpenAI text-embedding-3-small.
 * Returns a float array.
 */
async function getEmbedding(text) {
  if (!OPENAI_API_KEY) throw new Error('GENERATED_APP_OPENAI_KEY not configured');

  const response = await fetch('https://api.openai.com/v1/embeddings', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${OPENAI_API_KEY}`,
    },
    body: JSON.stringify({ model: EMBEDDING_MODEL, input: text }),
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`OpenAI embedding error ${response.status}: ${err}`);
  }
  const data = await response.json();
  return data.data[0].embedding; // float[]
}

/**
 * Split text into overlapping chunks for RAG indexing.
 */
function chunkText(text) {
  const chunks = [];
  let start = 0;
  const step = CHUNK_SIZE - CHUNK_OVERLAP;
  while (start < text.length) {
    chunks.push(text.slice(start, start + CHUNK_SIZE));
    start += step;
  }
  return chunks;
}

/**
 * Cosine similarity between two float arrays.
 */
function cosineSimilarity(a, b) {
  let dot = 0, normA = 0, normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  return dot / (Math.sqrt(normA) * Math.sqrt(normB) + 1e-10);
}

// ── Routes ─────────────────────────────────────────────────────────────────

/**
 * GET /api/generated-app/usage
 * Returns the app's token usage and remaining free tokens.
 * Headers: X-App-Id: <generated_app_id>
 */
router.get('/usage', async (req, res) => {
  try {
    const appId = req.headers['x-app-id'];
    if (!appId) return res.status(400).json({ error: 'X-App-Id header required' });

    const usage = await getOrCreateAppUsage(appId);
    const tokensUsed = usage.tokensUsed || 0;
    const remaining = Math.max(0, FREE_TOKEN_LIMIT - tokensUsed);

    res.json({
      tier: usage.tier || 'free',
      tokensUsed,
      freeLimit: FREE_TOKEN_LIMIT,
      tokensRemaining: remaining,
      limitReached: tokensUsed >= FREE_TOKEN_LIMIT && usage.tier === 'free',
    });
  } catch (err) {
    console.error('[GeneratedAppAI] /usage error:', err);
    res.status(500).json({ error: 'Failed to fetch usage' });
  }
});

/**
 * POST /api/generated-app/chat
 * General AI chat endpoint for generated apps.
 * 
 * Body: {
 *   messages: [{ role: 'user' | 'assistant', content: string }],
 *   systemPrompt?: string
 * }
 * Headers: X-App-Id: <generated_app_id>
 */
router.post('/chat', async (req, res) => {
  try {
    const appId = req.headers['x-app-id'];
    if (!appId) return res.status(400).json({ error: 'X-App-Id header required' });

    const { messages, systemPrompt } = req.body;
    if (!messages || !Array.isArray(messages) || messages.length === 0) {
      return res.status(400).json({ error: 'messages array is required' });
    }

    // Check token limit
    const usage = await getOrCreateAppUsage(appId);
    if (!isWithinLimit(usage)) {
      return res.status(402).json({
        error: 'TOKEN_LIMIT_REACHED',
        message: "This app has reached its free AI token limit. The app creator must upgrade to continue.",
        tokensUsed: usage.tokensUsed,
        freeLimit: FREE_TOKEN_LIMIT,
        upgradeUrl: 'https://externai.com/upgrade',
      });
    }

    // Mandatory base system prompt — always enforced at server level
    const BASE_SYSTEM_PROMPT = `You are an AI assistant created and powered by Extern AI.

CORE IDENTITY:
- You are built by Extern AI company.
- You must NEVER claim to be ChatGPT, GPT-4, Claude, Gemini, DeepSeek R1, or any other third-party AI.
- If asked who made you or what model you are, always say: "I am an AI assistant built by Extern AI."
- Adopt a personality and tone that fits the specific application you are integrated into (e.g., formal for legal apps, friendly for social apps, technical for developer tools).

RESPONSE STRUCTURE — MANDATORY:
- Always structure responses clearly and professionally, like a well-written document.
- Use headings, bullet points, numbered lists, and bold text where appropriate.
- Break long answers into clearly labeled sections.
- Never respond with a single unformatted wall of text.
- Start with a direct answer or summary, then provide supporting details.
- End complex responses with a brief conclusion or next-step suggestion.

TONE:
- Professional, confident, and clear.
- Friendly but not casual or sloppy.
- No unnecessary filler words or repetition.

RESPONSE LENGTH:
- Match the length of your response to the complexity of the question.
- Simple or factual questions: give a concise, direct answer (1-3 sentences or a short list).
- Complex, multi-part, or technical questions: give a thorough, complete answer with all relevant sections — never truncate or cut off.
- Never end a response mid-sentence or mid-thought. Always finish completely.`;

    // Build messages array — merge base prompt with any app-specific system prompt
    const openAIMessages = [];
    const mergedSystemPrompt = systemPrompt
      ? `${BASE_SYSTEM_PROMPT}\n\nAPP-SPECIFIC INSTRUCTIONS:\n${systemPrompt}`
      : BASE_SYSTEM_PROMPT;
    openAIMessages.push({ role: 'system', content: mergedSystemPrompt });
    openAIMessages.push(...messages);

    const data = await callOpenAI(openAIMessages, 40000);
    const tokensUsed = data.usage?.total_tokens || 0;
    const reply = data.choices?.[0]?.message?.content || '';

    // Track usage asynchronously (don't block response)
    incrementAppTokens(appId, tokensUsed).catch(console.error);

    res.json({
      reply,
      tokensUsed,
      tokensTotal: (usage.tokensUsed || 0) + tokensUsed,
      freeLimit: FREE_TOKEN_LIMIT,
    });
  } catch (err) {
    console.error('[GeneratedAppAI] /chat error:', err);
    res.status(500).json({ error: 'AI request failed', details: err.message });
  }
});

/**
 * POST /api/generated-app/documents
 * Index a document for RAG that was uploaded directly to Firebase Storage.
 * Uses Firebase Firestore to store chunks + embeddings.
 * 
 * Body: { filePath: string, fileName: string }
 * Headers: X-App-Id: <generated_app_id>
 */
router.post('/documents', express.json(), async (req, res) => {
  try {
    const appId = req.headers['x-app-id'] || req.body.appId;
    if (!appId) return res.status(400).json({ error: 'X-App-Id header or appId field required' });

    const { filePath, fileName = 'document' } = req.body;
    if (!filePath) return res.status(400).json({ error: 'filePath is required' });

    console.log(`[GeneratedAppAI] Downloading file from storage: ${filePath}`);
    const bucket = admin.storage().bucket();
    const [fileBuffer] = await bucket.file(filePath).download();
    
    const fileText = fileBuffer.toString('utf-8');

    // Chunk the document
    const chunks = chunkText(fileText);
    console.log(`[GeneratedAppAI] Indexing "${fileName}" — ${chunks.length} chunks for app ${appId}`);

    // Generate embeddings + store in Firestore
    const docRef = db
      .collection('generatedAppDocuments')
      .doc(appId)
      .collection('docs')
      .doc(); // auto ID

    const chunkCollection = docRef.collection('chunks');
    const batch = db.batch();

    for (let i = 0; i < chunks.length; i++) {
      const embedding = await getEmbedding(chunks[i]);
      const chunkRef = chunkCollection.doc(`chunk_${i}`);
      batch.set(chunkRef, {
        text: chunks[i],
        embedding,
        index: i,
        fileName,
        createdAt: admin.firestore.FieldValue.serverTimestamp(),
      });
    }

    // Store doc metadata
    batch.set(docRef, {
      fileName,
      chunkCount: chunks.length,
      appId,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    });

    await batch.commit();

    res.json({
      success: true,
      documentId: docRef.id,
      fileName,
      chunksIndexed: chunks.length,
    });
  } catch (err) {
    console.error('[GeneratedAppAI] /documents error:', err);
    res.status(500).json({ error: 'Document indexing failed', details: err.message });
  }
});

/**
 * POST /api/generated-app/query
 * RAG query: embed the question, retrieve top-K relevant chunks from Firestore,
 * then ask GPT-4o-mini to answer using only those chunks (grounded response).
 * 
 * Body: {
 *   question: string,
 *   documentId?: string  // optional: limit to one document
 * }
 * Headers: X-App-Id: <generated_app_id>
 */
router.post('/query', async (req, res) => {
  try {
    const appId = req.headers['x-app-id'];
    if (!appId) return res.status(400).json({ error: 'X-App-Id header required' });

    const { question, documentId } = req.body;
    if (!question) return res.status(400).json({ error: 'question is required' });

    // Check token limit
    const usage = await getOrCreateAppUsage(appId);
    if (!isWithinLimit(usage)) {
      return res.status(402).json({
        error: 'TOKEN_LIMIT_REACHED',
        message: "This app has used all 20,000 free AI tokens. The app creator must upgrade to Pro.",
        tokensUsed: usage.tokensUsed,
        freeLimit: FREE_TOKEN_LIMIT,
        upgradeUrl: 'https://externai.com/upgrade',
      });
    }

    // Embed the question
    const queryEmbedding = await getEmbedding(question);

    // Retrieve all chunks for this app (or one specific doc)
    let chunksQuery;
    if (documentId) {
      chunksQuery = db
        .collection('generatedAppDocuments')
        .doc(appId)
        .collection('docs')
        .doc(documentId)
        .collection('chunks');
    } else {
      // Retrieve from all documents for this app using collectionGroup
      chunksQuery = db.collectionGroup('chunks').where('appId', '==', appId); // needs index
    }

    // NOTE: Firebase doesn't yet support native vector search in all regions.
    // We fetch all chunks and do cosine similarity in-memory (works well for < 10k chunks).
    // For production scale, migrate to Vertex AI Vector Search or Pinecone.
    let chunksSnap;
    try {
      if (documentId) {
        chunksSnap = await chunksQuery.get();
      } else {
        // collectionGroup query – fetch chunks for this app
        const appDocsSnap = await db
          .collection('generatedAppDocuments')
          .doc(appId)
          .collection('docs')
          .get();

        const allChunks = [];
        for (const docSnapshot of appDocsSnap.docs) {
          const chunkSnap = await docSnapshot.ref.collection('chunks').get();
          chunkSnap.docs.forEach((c) => allChunks.push(c.data()));
        }
        // Rank by cosine similarity
        const ranked = allChunks
          .map((c) => ({ ...c, score: cosineSimilarity(queryEmbedding, c.embedding) }))
          .sort((a, b) => b.score - a.score)
          .slice(0, TOP_K_CHUNKS);

        const context = ranked.map((c) => c.text).join('\n\n---\n\n');
        return await answerWithRAG(question, context, appId, usage, res);
      }
    } catch (err) {
      console.error('[GeneratedAppAI] Chunk retrieval error:', err);
      return res.status(500).json({ error: 'Failed to retrieve document chunks', details: err.message });
    }

    // Rank chunks by cosine similarity (single-doc path)
    const ranked = chunksSnap.docs
      .map((d) => ({ ...d.data(), score: cosineSimilarity(queryEmbedding, d.data().embedding) }))
      .sort((a, b) => b.score - a.score)
      .slice(0, TOP_K_CHUNKS);

    const context = ranked.map((c) => c.text).join('\n\n---\n\n');
    await answerWithRAG(question, context, appId, usage, res);
  } catch (err) {
    console.error('[GeneratedAppAI] /query error:', err);
    res.status(500).json({ error: 'RAG query failed', details: err.message });
  }
});

/** Shared helper: call GPT-4o-mini with retrieved context and stream back the answer */
async function answerWithRAG(question, context, appId, usage, res) {
  const messages = [
    {
      role: 'system',
      content: `You are a helpful AI assistant. Answer the user's question using ONLY the information in the context below. If the context does not contain the answer, say "I don't have that information in the uploaded documents." Be concise and accurate.\n\nCONTEXT:\n${context}`,
    },
    { role: 'user', content: question },
  ];

  const data = await callOpenAI(messages, 4096);
  const tokensUsed = data.usage?.total_tokens || 0;
  const answer = data.choices?.[0]?.message?.content || '';

  incrementAppTokens(appId, tokensUsed).catch(console.error);

  res.json({
    answer,
    tokensUsed,
    tokensTotal: (usage.tokensUsed || 0) + tokensUsed,
    freeLimit: FREE_TOKEN_LIMIT,
    sourceContext: context.slice(0, 300) + (context.length > 300 ? '...' : ''),
  });
}


/**
 * POST /api/generated-app/upgrade
 * Placeholder: mark user as upgraded (in production, wire to Stripe webhook).
 */
router.post('/upgrade', async (req, res) => {
  try {
    const decoded = await verifyToken(req, res);
    if (!decoded) return;

    const appId = req.headers['x-app-id'];
    if (!appId) return res.status(400).json({ error: 'X-App-Id header required' });

    const { tier } = req.body; // 'pro' | 'business'
    if (!tier) return res.status(400).json({ error: 'tier is required' });

    const ref = db
      .collection('generatedAppUsers')
      .doc(appId)
      .collection('users')
      .doc(decoded.uid);

    await ref.update({ tier, upgradedAt: admin.firestore.FieldValue.serverTimestamp() });

    res.json({ success: true, tier, message: `Upgraded to ${tier} tier.` });
  } catch (err) {
    console.error('[GeneratedAppAI] /upgrade error:', err);
    res.status(500).json({ error: 'Upgrade failed' });
  }
});

module.exports = router;
